blank_issues_enabled: false
contact_links:
  - name: Other Concerns
    url: https://github.com/orgs/Zen-Focus/discussions
    about: If you have any general questions or ideas, please add them to the repository's discussion tab instead
